### ISSUE TITLE
Compilation Failure on Linux Kernel 6.14.x (Ubuntu 24.04/Noble) due to CFG80211 and VFS API Changes

### ISSUE THREAD

**Issue by DRCRecoveryData** [lwfinger/rtl8852au#135]
### 🐞 Description of the Issue

<img width="3540" height="3540" alt="Image" src="https://github.com/user-attachments/assets/e3c4b521-1665-4bd0-90a0-cefcdb3b7ce4" />

![image](https://github.com/user-attachments/assets/7195cdc9-ec80-4191-9e59-be8c49e632a4)

![image](https://github.com/user-attachments/assets/8ebd4df9-bd56-4772-a2b4-92451e31c7eb)

The driver fails to compile on recent Linux kernels (6.14.x and newer, specifically tested on `6.14.0-33-generic`) with the following error types, indicating changes in the kernel's wireless and filesystem APIs.

### 💻 Environment

  * **Linux Distribution:** Ubuntu (or your specific distribution)
  * **OS Version:** 24.04 (Noble Numbat)
  * **Kernel Version:** `6.14.0-33-generic`
  * **Device ID:** `Bus 001 Device 007: ID 0bda:8832 Realtek Semiconductor Corp. 802.11ac WLAN Adapter`
  * **Driver Branch/Commit:** [Specify the branch you cloned, e.g., `master` or a specific commit hash]

### 🚨 Compilation Errors Encountered (Summary)

The primary compilation failures were due to three main issues:

1.  **VFS/Kernel API Change (Linux 6.0+):** `MODULE_IMPORT_NS(VFS);` is incompatible.
2.  **CFG80211 Signature Mismatch:** Function signatures for `get_tx_power` and `set_monitor_channel` in `os_dep/linux/ioctl_cfg80211.c` do not match the `wiphy_ops` structure definition in the new kernel headers.

### 🔧 Workaround (Successful Patch)

The following sequence of patches was required to successfully compile and install the driver:

```bash
# Fix 1: VFS MODULE_IMPORT_NS
sed -i 's/^\(\s*MODULE_IMPORT_NS.*\)$/\/*\1 *\//' os_dep/osdep_service_linux.c

# Fix 2 & 3: CFG80211 Signature and Pointer Mismatches
# Patch Function Definitions (to align with kernel expectation)
sed -i 's/cfg80211_rtw_get_tx_power(struct wiphy *wiphy, struct wireless_dev *wdev, int *tx_power)/cfg80211_rtw_get_tx_power(struct wiphy *wiphy, struct wireless_dev *wdev, unsigned int type, int *tx_power)/' os_dep/linux/ioctl_cfg80211.c
sed -i 's/cfg80211_rtw_set_monitor_channel(struct wiphy *wiphy, struct cfg80211_chan_def *chan_def)/cfg80211_rtw_set_monitor_channel(struct wiphy *wiphy, struct net_device *dev, struct cfg80211_chan_def *chan_def)/' os_dep/linux/ioctl_cfg80211.c

# Patch Structure Assignments (Workaround to pass compilation)
sed -i 's/\.get_tx_power = cfg80211_rtw_get_tx_power,/\.get_tx_power = NULL,/' os_dep/linux/ioctl_cfg80211.c
sed -i 's/\.set_monitor_channel = cfg80211_rtw_set_monitor_channel,/\.set_monitor_channel = NULL,/' os_dep/linux/ioctl_cfg80211.c
```
