### ISSUE TITLE
Install not working on Rocky Linux 9.4 : osdep_service_linux.h:488:9: error: implicit declaration of function ‘complete_and_exit’ 

### ISSUE THREAD

**Issue by simenon** [lwfinger/rtl8852au#101]
Getting the following compilation error on Rocky Linux with kernel release 5.14.0-427.13.1.el9_4.x86_64

```
make
#rm -f .symvers.8852au
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.14.0-427.13.1.el9_4.x86_64/build M=/tmp/rtl8852au  modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-427.13.1.el9_4.x86_64'
  CC [M]  /tmp/rtl8852au/os_dep/osdep_service.o
In file included from /tmp/rtl8852au/include/osdep_service.h:42,
                 from /tmp/rtl8852au/include/drv_types.h:25,
                 from /tmp/rtl8852au/os_dep/osdep_service.c:17:
/tmp/rtl8852au/include/osdep_service_linux.h: In function ‘rtw_thread_exit’:
/tmp/rtl8852au/include/osdep_service_linux.h:488:9: error: implicit declaration of function ‘complete_and_exit’ [-Werror=implicit-function-declaration]
  488 |         complete_and_exit(comp, 0);
      |         ^~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:299: /tmp/rtl8852au/os_dep/osdep_service.o] Error 1
make[1]: *** [Makefile:1934: /tmp/rtl8852au] Error 2
make[1]: Leaving directory '/usr/src/kernels/5.14.0-427.13.1.el9_4.x86_64'
make: *** [Makefile:639: modules] Error 2
```

**Comment by simenon** [comment]
Further research pointed me too https://github.com/lwfinger/rtl8852au/pull/72 and i can confirm that that version works

**Comment by bmx666** [comment]
Hi @simenon , there is a bad news, please read https://github.com/lwfinger/rtl8188eu/issues/458
